title: Class'Code
email: contact@classcode.com

collections:
  resources:
    output: true
  paths:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "resources"
    values:
      layout: "resource"
  - scope:
      path: ""
      type: "paths"
    values:
      layout: "path"
